/**
 * @file PI_Motor_Control.ino
 * @brief PI speed control for a DC motor using an Arduino UNO R4,
 *        a slotted disc and an F249 forked light barrier.
 *
 * The rotational speed is measured using a slotted disc mounted
 * on the motor shaft. Every interruption of the light beam
 * generates a pulse which is detected via an external interrupt.
 *
 * A PI controller calculates the PWM output signal based on the
 * difference between the desired speed and the measured speed.
 *
 * Hardware:
 * - Arduino UNO R4
 * - DC motor
 * - Motor driver (e.g. L298N)
 * - F249 forked light barrier
 * - Slotted disc with 20 holes
 *
 * Author: Bjarne Janssen 
 * Date: 2026
 */


/**
 * @brief Counts the detected sensor pulses.
 *
 * This variable is increased inside the interrupt service routine
 * every time the light barrier detects a falling edge.
 *
 * The variable must be declared as volatile because it is modified
 * asynchronously inside an interrupt routine.
 */
volatile int impulse = 0;


/**
 * @brief Digital input pin for the F249 light barrier.
 */
const int sensorPin = 2;


/**
 * @brief PWM output pin for motor control.
 *
 * The PWM signal controls the motor driver and therefore
 * the effective motor voltage.
 */
const int motorPin = 9;


/**
 * @brief Number of holes inside the slotted disc.
 *
 * One full rotation produces exactly this number of pulses.
 */
const int loecher = 20;


/**
 * @brief Desired rotational speed in revolutions per minute.
 */
float sollDrehzahl = 300.0;


/**
 * @brief Measured rotational speed in revolutions per minute.
 */
float istDrehzahl = 0.0;


/**
 * @brief Proportional gain of the PI controller.
 *
 * A higher value increases the dynamic response but may
 * also lead to oscillations.
 */
float Kp = 0.8;


/**
 * @brief Integral gain of the PI controller.
 *
 * The integral part compensates steady-state control errors.
 */
float Ki = 0.3;


/**
 * @brief Current control error.
 *
 * Difference between desired speed and measured speed.
 */
float fehler = 0.0;


/**
 * @brief Integral accumulation of the control error.
 *
 * This value continuously sums the error over time.
 */
float integral = 0.0;


/**
 * @brief Stores the timestamp of the last control cycle.
 *
 * Used to generate a fixed controller sampling time.
 */
unsigned long letzteZeit = 0;


/**
 * @brief Initializes the hardware and interrupt configuration.
 *
 * This function configures:
 * - Serial communication
 * - Sensor input pin
 * - PWM output pin
 * - External interrupt for pulse detection
 */
void setup() {

    /* Initialize serial communication */
    Serial.begin(115200);

    /* Configure sensor input with internal pull-up resistor */
    pinMode(sensorPin, INPUT_PULLUP);

    /* Configure PWM output pin */
    pinMode(motorPin, OUTPUT);

    /**
     * Configure external interrupt.
     *
     * The interrupt is triggered on every falling edge
     * generated by the light barrier.
     */
    attachInterrupt(
        digitalPinToInterrupt(sensorPin),
        impulsZaehler,
        FALLING
    );
}


/**
 * @brief Main control loop.
 *
 * Every 100 ms the following operations are executed:
 * 1. Calculate the current rotational speed
 * 2. Determine the control error
 * 3. Calculate the PI controller output
 * 4. Update the PWM signal
 * 5. Print diagnostic information
 */
void loop() {

    /* Read current system time */
    unsigned long aktuelleZeit = millis();

    /**
     * Execute the controller every 100 ms.
     *
     * This creates a fixed sampling period
     * for the PI controller.
     */
    if (aktuelleZeit - letzteZeit >= 100) {

        /**
         * Calculate rotational speed.
         *
         * Formula:
         * RPM = (impulses * 600) / number_of_holes
         *
         * Explanation:
         * - Measurement interval = 100 ms
         * - 600 converts the value to revolutions per minute
         */
        istDrehzahl = (impulse * 600.0) / loecher;

        /* Calculate control deviation */
        fehler = sollDrehzahl - istDrehzahl;

        /**
         * Calculate integral component.
         *
         * The error is integrated over time in order
         * to eliminate permanent control deviations.
         */
        integral += fehler * 0.1;

        /**
         * Calculate PI controller output.
         *
         * Controller equation:
         * u(t) = Kp * e(t) + Ki * integral(e(t))
         */
        float stellgroesse =
              (Kp * fehler) +
              (Ki * integral);

        /**
         * Limit PWM signal.
         *
         * PWM values for analogWrite()
         * must remain between 0 and 255.
         */
        stellgroesse = constrain(stellgroesse, 0, 255);

        /* Apply PWM signal to motor */
        analogWrite(motorPin, (int)stellgroesse);

        /**
         * Output diagnostic data to serial monitor.
         *
         * This can be used to analyze:
         * - controller response
         * - transient behavior
         * - oscillations
         * - steady-state accuracy
         */
        Serial.print("Target RPM: ");
        Serial.print(sollDrehzahl);

        Serial.print(" | Actual RPM: ");
        Serial.print(istDrehzahl);

        Serial.print(" | PWM: ");
        Serial.println(stellgroesse);

        /* Reset pulse counter for next measurement cycle */
        impulse = 0;

        /* Store current timestamp */
        letzteZeit = aktuelleZeit;
    }
}


/**
 * @brief Interrupt Service Routine (ISR) for pulse detection.
 *
 * This function is automatically called whenever
 * the light barrier detects a falling edge.
 *
 * The ISR should remain as short as possible in order
 * to guarantee stable real-time behavior.
 */
void impulsZaehler() {

    impulse++;
}